### PR TITLE
Use API Blueprint as a docs for a ToDo app API

### PR DESCRIPTION
**Pull request by AleksSenkou**
Here is [API Blueprint](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#def-response-section) setup: it does not require additional node module and gratefully previewed via github and text editors (you may need to setup extension, for ex: [sublime plugin](https://github.com/apiaryio/api-blueprint-sublime-plugin))

Props:
* [x] Docs can be viewed without html-file, just read markdown
image

Note: markdown can be adjusted for better look and navigation

* [x] Dredd can be used for unit testing of endpoints (it takes info .apib file and runs specs based on response and request expecttions). Will be implemented in a separate PR

### CODE REVIEW

**Comment by AleksSenkou** [comment]
[I as developer want to generate documentation for api automatically](https://trello.com/c/Xr8uNixQ/7-i-as-developer-want-to-generate-documentation-for-api-automatically)

**Review by DDKatch — APPROVED** [review]
LGTM 👍 , going to rework our tests according to this 😉

**Comment by AleksSenkou** [comment]
@DDKatch no need to do it, sorry for not specifying it, but I've already reworked our tests 😉

**Comment by nikitasakov** [comment]
👍

**Pull request merged**
