### PR TITLE
Make eslint versions consistent

### PR DESCRIPTION
**Pull request by AleksSenkou**
**The issue:**
Babel-eslint:
image

Eslint:
image

**Changes:**
* [x] Move client package scripts to the top of configs for consistency
* [x] Use relevant babel-eslint and eslint versions

**Note:**
You may want to run ```rm -rf node_modules && yarn --ignore-engines``` after these changes

### CODE REVIEW

**Review by nikitasakau — APPROVED** [review]
I think looks good

**Comment by AleksSenkou** [comment]
[When I install dev dependencies, I'd like them to not raise errors, so I can start developing the app easily](https://trello.com/c/z1V9Iu8z/23-when-i-install-dev-dependencies-id-like-them-to-not-raise-errors-so-i-can-start-developing-the-app-easily)

**Comment by AleksSenkou** [comment]
@DDKatch @nikitasakov just curious: have you received notification about the review as `cuties`?

**Comment by nikitasakov** [comment]
> @DDKatch @nikitasakov just curious: have you received notification about the review as `cuties`?

Yes, "@AleksSenkou requested review from @datarockets/cuties on: #6 Add basic README with tools, development sections."

**Comment by AleksSenkou** [comment]
Great!

**Comment by DDKatch** [comment]
LGTM

**Pull request merged**
